# Generated by Django 3.0.8 on 2021-05-18 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChosenDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chosen_orders', to='menu.Dish', verbose_name='dish')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chosen_dishes', to='order.Order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'order detail',
                'verbose_name_plural': 'order details',
                'unique_together': {('order', 'dish')},
            },
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
    ]
