# Generated by Django 3.0.8 on 2021-05-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210518_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.CharField(blank=True, help_text='Space to write the order customizations.', max_length=200, verbose_name='note'),
        ),
    ]
