# Generated by Django 3.0.8 on 2021-05-18 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('country', models.CharField(choices=[('AR', 'Argentina'), ('BR', 'Brazil'), ('CA', 'Canada'), ('CL', 'Chile'), ('CO', 'Colombia'), ('CR', 'Costa Rica'), ('EC', 'Ecuador'), ('MX', 'Mexico'), ('PA', 'Panama'), ('PY', 'Paraguay'), ('PE', 'Peru'), ('US', 'United States'), ('UY', 'Uruguay')], db_index=True, help_text='Country where the employee currently works.', max_length=2, verbose_name='country')),
                ('slack_id', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='slack member id')),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
            },
        ),
    ]
