# Generated by Django 3.0.8 on 2021-05-18 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('type', models.IntegerField(choices=[(1, 'Main course'), (2, 'Salad'), (3, 'Dessert')], verbose_name='type')),
            ],
            options={
                'verbose_name': 'dish',
                'verbose_name_plural': 'dishes',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('date', models.DateField(help_text='Date when the menu will be available.', verbose_name='date')),
                ('country', models.CharField(choices=[('AR', 'Argentina'), ('BR', 'Brazil'), ('CA', 'Canada'), ('CL', 'Chile'), ('CO', 'Colombia'), ('CR', 'Costa Rica'), ('EC', 'Ecuador'), ('MX', 'Mexico'), ('PA', 'Panama'), ('PY', 'Paraguay'), ('PE', 'Peru'), ('US', 'United States'), ('UY', 'Uruguay')], db_index=True, help_text='Country where the menu will be available.', max_length=2, verbose_name='country')),
                ('time_limit', models.TimeField(default=datetime.time(11, 0), help_text='Deadline to place an order.', verbose_name='time limit')),
                ('published', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='published')),
                ('dishes', models.ManyToManyField(to='menu.Dish', verbose_name='dishes')),
            ],
            options={
                'verbose_name': 'menu',
                'verbose_name_plural': 'menus',
                'unique_together': {('date', 'country')},
            },
        ),
    ]
